server:
  port: 9001 #æœåŠ¡ç«¯å£
spring:
  application:
    name: tensquare-base #æœåŠ¡å?
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.18.77:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true